In [2]:
import pandas as pd

In [135]:
ano2023 = pd.read_csv("total_abandono_alunos_estados/abandono_escolar_por_estado2023.csv")
ano2023

,Estado,Total_Fundamental,Total_Medio,Total_Geral,Taxa_Abandono_EF2023,Taxa_Abandono_EM2023,Abandono_EF,Abandono_EM,Total_Abandonos
0,Acre,147350.0,40216.0,187566.0,2.5,6.1,3684,2453,6137
1,Alagoas,439014.0,120878.0,559892.0,0.6,2.6,2634,3143,5777
2,Amapá,131948.0,32435.0,164383.0,1.1,4.8,1451,1557,3008
3,Amazonas,692623.0,189771.0,882394.0,1.3,4.2,9004,7970,16974
4,Bahia,1865574.0,517073.0,2382647.0,1.6,4.8,29849,24820,54669
5,Ceará,1134636.0,358735.0,1493371.0,0.2,2.0,2269,7175,9444
6,Distrito Federal,361438.0,111437.0,472875.0,0.5,3.0,1807,3343,5150
7,Espírito Santo,498357.0,126068.0,624425.0,0.3,1.6,1495,2017,3512
8,Goiás,868222.0,224130.0,1092352.0,0.3,0.6,2605,1345,3950
9,Maranhão,1045700.0,283486.0,1329186.0,1.0,3.4,10457,9639,20096
10,Mato Grosso,507089.0,137021.0,644110.0,0.2,2.5,1014,3426,4440
11,Mato Grosso do Sul,393616.0,103814.0,497430.0,0.5,3.6,1968,3737,5705
12,Minas Gerais,2343279.0,716517.0,3059796.0,0.7,5.0,16403,35826,52229
13,Paraná,1365869.0,403394.0,1769263.0,0.1,0.6,1366,2420,3786
14,Paraíba,523996.0,140067.0,664063.0,1.3,6.5,6812,9104,15916
15,Pará,1331723.0,324258.0,1655981.0,1.7,0.4,22639,1297,23936
16,Pernambuco,1229419.0,338436.0,1567855.0,0.4,0.9,4918,3046,7964
17,Piauí,439111.0,128628.0,567739.0,0.5,2.0,2196,2573,4769
18,Rio Grande do Norte,437133.0,127507.0,564640.0,1.5,8.1,6557,10328,16885
19,Rio Grande do Sul,1255794.0,349367.0,1605161.0,0.8,7.7,10046,26901,36947
20,Rio de Janeiro,1945098.0,554816.0,2499914.0,0.6,4.2,11671,23302,34973
21,Rondônia,227246.0,71396.0,298642.0,0.7,3.9,1591,2784,4375
22,Roraima,111096.0,27821.0,138917.0,1.3,4.3,1444,1196,2640
23,Santa Catarina,941272.0,267040.0,1208312.0,0.3,4.4,2824,11750,14574
24,Sergipe,305930.0,83603.0,389533.0,0.9,2.6,2753,2174,4927
25,São Paulo,5343271.0,1832726.0,7175997.0,0.4,2.8,21373,51316,72689
26,Tocantins,222404.0,66103.0,288507.0,0.4,1.8,890,1190,2080

In [136]:
novo2023= ano2023[['Estado','Abandono_EF','Abandono_EM']]
novo2023

                 Estado  Abandono_EF  Abandono_EM
0                  Acre         3684         2453
1               Alagoas         2634         3143
2                 Amapá         1451         1557
3              Amazonas         9004         7970
4                 Bahia        29849        24820
5                 Ceará         2269         7175
6      Distrito Federal         1807         3343
7        Espírito Santo         1495         2017
8                 Goiás         2605         1345
9              Maranhão        10457         9639
10          Mato Grosso         1014         3426
11   Mato Grosso do Sul         1968         3737
12         Minas Gerais        16403        35826
13               Paraná         1366         2420
14              Paraíba         6812         9104
15                 Pará        22639         1297
16           Pernambuco         4918         3046
17                Piauí         2196         2573
18  Rio Grande do Norte         6557        10328
19    Rio Grande do Sul        10046        26901
20       Rio de Janeiro        11671        23302
21             Rondônia         1591         2784
22              Roraima         1444         1196
23       Santa Catarina         2824        11750
24              Sergipe         2753         2174
25            São Paulo        21373        51316
26            Tocantins          890         1190

In [143]:
dados = pd.read_csv("totais por ano.csv")
dados

,Estado,Abandono_EF2007,Abandono_EM2007,Abandono_EF2008,Abandono_EM2008,Abandono_EF2009,Abandono_EM2009,Abandono_EF2010,Abandono_EM2010,Abandono_EF2011,...,Abandono_EF2019,Abandono_EM2019,Abandono_EF2020,Abandono_EM2020,Abandono_EF2021,Abandono_EM2021,Abandono_EF2022,Abandono_EM2022,Abandono_EF2023,Abandono_EM2023
0,Acre,4470,5512,6739,5563,7147,5110,6316,5553,5655,...,3284,2439,2820,1296,3978,2522,4040,3706,3684,2453
1,Alagoas,48121,32874,37666,28108,33893,32474,26497,29045,46589,...,7136,7088,5112,587,5047,9718,7253,8543,2634,3143
2,Amapá,6930,8513,4976,8183,2142,7810,2892,7385,4585,...,2720,3200,1887,759,2811,2560,2253,2235,1451,1557
3,Amazonas,51244,21077,49366,28578,44081,27148,39370,20588,44493,...,16804,20923,5601,208,17569,11622,16726,15592,9004,7970
4,Bahia,185146,161873,154710,160581,115242,145913,80850,114268,130583,...,51768,38686,40891,5574,64250,67370,55404,66648,29849,24820
5,Ceará,50550,78052,41495,72404,34214,68375,23773,53864,37069,...,8246,12609,10488,10149,3484,6984,3460,10423,2269,7175
6,Distrito Federal,6205,9456,4688,5294,2943,10915,2936,9599,4601,...,2999,4071,746,671,369,1168,2190,4119,1807,3343
7,Espírito Santo,8388,21546,6696,19630,5496,18341,4867,11732,9122,...,2513,2399,2510,2641,3521,2970,2510,2287,1495,2017
8,Goiás,33034,53968,25651,48099,20732,36697,14873,35722,24686,...,5214,4506,6029,4323,5130,3103,4314,3987,2605,1345
9,Maranhão,65417,69624,63601,67087,41526,54665,36802,56662,46758,...,20762,13642,25851,15031,27816,17870,18438,13313,10457,9639
10,Mato Grosso,19031,30531,13108,34355,8188,26731,3425,19425,5330,...,2869,13712,955,980,1946,8370,2506,14991,1014,3426
11,Mato Grosso do Sul,9386,14765,7303,12941,5914,12558,5172,13567,11519,...,4367,6209,1176,734,1568,1537,2754,4909,1968,3737
12,Minas Gerais,45839,121864,35440,110137,28300,95677,18224,90330,58591,...,14767,34551,46779,54496,19257,24243,19261,48140,16403,35826
13,Paraná,8513,53966,8589,59503,6798,46954,4982,37882,25601,...,7022,12640,7040,13190,2697,4544,5521,15428,1366,2420
14,Paraíba,52850,38056,49697,37791,37009,34677,27766,32606,42378,...,12619,8534,13469,3320,9737,4880,11768,13579,6812,9104
15,Pará,150059,86555,106464,84793,92796,84618,79207,77801,78346,...,41136,35984,23698,2481,43089,61090,42409,39785,22639,1297
16,Pernambuco,93803,122590,73627,94676,58743,71280,36042,53255,60789,...,11558,4692,16475,1029,7499,4783,9973,5130,4918,3046
17,Piauí,26389,47624,25409,55156,16459,47734,13949,36665,18688,...,6112,9273,7329,6667,6438,5964,5882,10281,2196,2573
18,Rio Grande do Norte,26121,48100,25860,43361,20517,38538,16631,32148,28255,...,9188,9381,7180,748,16565,19720,8945,13384,6557,10328
19,Rio Grande do Sul,18083,76730,11293,70459,9464,64161,9241,58882,21047,...,11527,17778,3808,21285,18870,32558,12635,34683,10046,26901
20,Rio de Janeiro,69817,115089,64951,118160,56842,107419,41741,95427,48076,...,19763,33364,23616,3000,17509,11045,15687,31599,11671,23302
21,Rondônia,9995,9616,6661,9671,4776,8550,4104,8381,8691,...,2872,3449,5305,1441,2693,3456,2608,4752,1591,2784
22,Roraima,1673,1886,1021,1800,865,1786,1099,1514,2434,...,1943,1675,729,194,1547,1282,2034,2483,1444,1196
23,Santa Catarina,4652,21934,2771,22845,2696,21245,1761,23332,7792,...,3461,12387,1753,9168,3601,19724,2769,13232,2824,11750
24,Sergipe,24047,21591,17186,21370,13022,17478,7833,16760,16646,...,6571,4815,3549,1553,4489,2579,5346,3909,2753,2174
25,São Paulo,18220,96517,18227,85519,12201,80846,24104,97506,53342,...,21637,31038,10828,6132,32381,54267,21519,58702,21373,51316
26,Tocantins,5336,10419,4426,10081,3571,7256,2164,6765,4253,...,2171,2676,2593,2714,1366,2260,1122,2363,890,1190

In [138]:
merged_df = pd.merge(dados, novo2023, left_on='Estado', right_on='Estado', how='outer')

In [139]:
merged_df

,Estado,Abandono_EF2007,Abandono_EM2007,Abandono_EF2008,Abandono_EM2008,Abandono_EF2009,Abandono_EM2009,Abandono_EF2010,Abandono_EM2010,Abandono_EF2011,...,Abandono_EF2019,Abandono_EM2019,Abandono_EF2020,Abandono_EM2020,Abandono_EF2021,Abandono_EM2021,Abandono_EF2022,Abandono_EM2022,Abandono_EF,Abandono_EM
0,Acre,4470,5512,6739,5563,7147,5110,6316,5553,5655,...,3284,2439,2820,1296,3978,2522,4040,3706,3684,2453
1,Alagoas,48121,32874,37666,28108,33893,32474,26497,29045,46589,...,7136,7088,5112,587,5047,9718,7253,8543,2634,3143
2,Amapá,6930,8513,4976,8183,2142,7810,2892,7385,4585,...,2720,3200,1887,759,2811,2560,2253,2235,1451,1557
3,Amazonas,51244,21077,49366,28578,44081,27148,39370,20588,44493,...,16804,20923,5601,208,17569,11622,16726,15592,9004,7970
4,Bahia,185146,161873,154710,160581,115242,145913,80850,114268,130583,...,51768,38686,40891,5574,64250,67370,55404,66648,29849,24820
5,Ceará,50550,78052,41495,72404,34214,68375,23773,53864,37069,...,8246,12609,10488,10149,3484,6984,3460,10423,2269,7175
6,Distrito Federal,6205,9456,4688,5294,2943,10915,2936,9599,4601,...,2999,4071,746,671,369,1168,2190,4119,1807,3343
7,Espírito Santo,8388,21546,6696,19630,5496,18341,4867,11732,9122,...,2513,2399,2510,2641,3521,2970,2510,2287,1495,2017
8,Goiás,33034,53968,25651,48099,20732,36697,14873,35722,24686,...,5214,4506,6029,4323,5130,3103,4314,3987,2605,1345
9,Maranhão,65417,69624,63601,67087,41526,54665,36802,56662,46758,...,20762,13642,25851,15031,27816,17870,18438,13313,10457,9639
10,Mato Grosso,19031,30531,13108,34355,8188,26731,3425,19425,5330,...,2869,13712,955,980,1946,8370,2506,14991,1014,3426
11,Mato Grosso do Sul,9386,14765,7303,12941,5914,12558,5172,13567,11519,...,4367,6209,1176,734,1568,1537,2754,4909,1968,3737
12,Minas Gerais,45839,121864,35440,110137,28300,95677,18224,90330,58591,...,14767,34551,46779,54496,19257,24243,19261,48140,16403,35826
13,Paraná,8513,53966,8589,59503,6798,46954,4982,37882,25601,...,7022,12640,7040,13190,2697,4544,5521,15428,1366,2420
14,Paraíba,52850,38056,49697,37791,37009,34677,27766,32606,42378,...,12619,8534,13469,3320,9737,4880,11768,13579,6812,9104
15,Pará,150059,86555,106464,84793,92796,84618,79207,77801,78346,...,41136,35984,23698,2481,43089,61090,42409,39785,22639,1297
16,Pernambuco,93803,122590,73627,94676,58743,71280,36042,53255,60789,...,11558,4692,16475,1029,7499,4783,9973,5130,4918,3046
17,Piauí,26389,47624,25409,55156,16459,47734,13949,36665,18688,...,6112,9273,7329,6667,6438,5964,5882,10281,2196,2573
18,Rio Grande do Norte,26121,48100,25860,43361,20517,38538,16631,32148,28255,...,9188,9381,7180,748,16565,19720,8945,13384,6557,10328
19,Rio Grande do Sul,18083,76730,11293,70459,9464,64161,9241,58882,21047,...,11527,17778,3808,21285,18870,32558,12635,34683,10046,26901
20,Rio de Janeiro,69817,115089,64951,118160,56842,107419,41741,95427,48076,...,19763,33364,23616,3000,17509,11045,15687,31599,11671,23302
21,Rondônia,9995,9616,6661,9671,4776,8550,4104,8381,8691,...,2872,3449,5305,1441,2693,3456,2608,4752,1591,2784
22,Roraima,1673,1886,1021,1800,865,1786,1099,1514,2434,...,1943,1675,729,194,1547,1282,2034,2483,1444,1196
23,Santa Catarina,4652,21934,2771,22845,2696,21245,1761,23332,7792,...,3461,12387,1753,9168,3601,19724,2769,13232,2824,11750
24,Sergipe,24047,21591,17186,21370,13022,17478,7833,16760,16646,...,6571,4815,3549,1553,4489,2579,5346,3909,2753,2174
25,São Paulo,18220,96517,18227,85519,12201,80846,24104,97506,53342,...,21637,31038,10828,6132,32381,54267,21519,58702,21373,51316
26,Tocantins,5336,10419,4426,10081,3571,7256,2164,6765,4253,...,2171,2676,2593,2714,1366,2260,1122,2363,890,1190

In [140]:
totalTotal= merged_df

In [141]:
totalTotal

,Estado,Abandono_EF2007,Abandono_EM2007,Abandono_EF2008,Abandono_EM2008,Abandono_EF2009,Abandono_EM2009,Abandono_EF2010,Abandono_EM2010,Abandono_EF2011,...,Abandono_EF2019,Abandono_EM2019,Abandono_EF2020,Abandono_EM2020,Abandono_EF2021,Abandono_EM2021,Abandono_EF2022,Abandono_EM2022,Abandono_EF,Abandono_EM
0,Acre,4470,5512,6739,5563,7147,5110,6316,5553,5655,...,3284,2439,2820,1296,3978,2522,4040,3706,3684,2453
1,Alagoas,48121,32874,37666,28108,33893,32474,26497,29045,46589,...,7136,7088,5112,587,5047,9718,7253,8543,2634,3143
2,Amapá,6930,8513,4976,8183,2142,7810,2892,7385,4585,...,2720,3200,1887,759,2811,2560,2253,2235,1451,1557
3,Amazonas,51244,21077,49366,28578,44081,27148,39370,20588,44493,...,16804,20923,5601,208,17569,11622,16726,15592,9004,7970
4,Bahia,185146,161873,154710,160581,115242,145913,80850,114268,130583,...,51768,38686,40891,5574,64250,67370,55404,66648,29849,24820
5,Ceará,50550,78052,41495,72404,34214,68375,23773,53864,37069,...,8246,12609,10488,10149,3484,6984,3460,10423,2269,7175
6,Distrito Federal,6205,9456,4688,5294,2943,10915,2936,9599,4601,...,2999,4071,746,671,369,1168,2190,4119,1807,3343
7,Espírito Santo,8388,21546,6696,19630,5496,18341,4867,11732,9122,...,2513,2399,2510,2641,3521,2970,2510,2287,1495,2017
8,Goiás,33034,53968,25651,48099,20732,36697,14873,35722,24686,...,5214,4506,6029,4323,5130,3103,4314,3987,2605,1345
9,Maranhão,65417,69624,63601,67087,41526,54665,36802,56662,46758,...,20762,13642,25851,15031,27816,17870,18438,13313,10457,9639
10,Mato Grosso,19031,30531,13108,34355,8188,26731,3425,19425,5330,...,2869,13712,955,980,1946,8370,2506,14991,1014,3426
11,Mato Grosso do Sul,9386,14765,7303,12941,5914,12558,5172,13567,11519,...,4367,6209,1176,734,1568,1537,2754,4909,1968,3737
12,Minas Gerais,45839,121864,35440,110137,28300,95677,18224,90330,58591,...,14767,34551,46779,54496,19257,24243,19261,48140,16403,35826
13,Paraná,8513,53966,8589,59503,6798,46954,4982,37882,25601,...,7022,12640,7040,13190,2697,4544,5521,15428,1366,2420
14,Paraíba,52850,38056,49697,37791,37009,34677,27766,32606,42378,...,12619,8534,13469,3320,9737,4880,11768,13579,6812,9104
15,Pará,150059,86555,106464,84793,92796,84618,79207,77801,78346,...,41136,35984,23698,2481,43089,61090,42409,39785,22639,1297
16,Pernambuco,93803,122590,73627,94676,58743,71280,36042,53255,60789,...,11558,4692,16475,1029,7499,4783,9973,5130,4918,3046
17,Piauí,26389,47624,25409,55156,16459,47734,13949,36665,18688,...,6112,9273,7329,6667,6438,5964,5882,10281,2196,2573
18,Rio Grande do Norte,26121,48100,25860,43361,20517,38538,16631,32148,28255,...,9188,9381,7180,748,16565,19720,8945,13384,6557,10328
19,Rio Grande do Sul,18083,76730,11293,70459,9464,64161,9241,58882,21047,...,11527,17778,3808,21285,18870,32558,12635,34683,10046,26901
20,Rio de Janeiro,69817,115089,64951,118160,56842,107419,41741,95427,48076,...,19763,33364,23616,3000,17509,11045,15687,31599,11671,23302
21,Rondônia,9995,9616,6661,9671,4776,8550,4104,8381,8691,...,2872,3449,5305,1441,2693,3456,2608,4752,1591,2784
22,Roraima,1673,1886,1021,1800,865,1786,1099,1514,2434,...,1943,1675,729,194,1547,1282,2034,2483,1444,1196
23,Santa Catarina,4652,21934,2771,22845,2696,21245,1761,23332,7792,...,3461,12387,1753,9168,3601,19724,2769,13232,2824,11750
24,Sergipe,24047,21591,17186,21370,13022,17478,7833,16760,16646,...,6571,4815,3549,1553,4489,2579,5346,3909,2753,2174
25,São Paulo,18220,96517,18227,85519,12201,80846,24104,97506,53342,...,21637,31038,10828,6132,32381,54267,21519,58702,21373,51316
26,Tocantins,5336,10419,4426,10081,3571,7256,2164,6765,4253,...,2171,2676,2593,2714,1366,2260,1122,2363,890,1190

In [142]:
totalTotal.to_csv("totais por ano.csv", sep=",", index=False)

### parte da bolsa familia

In [93]:
bolsa2015= pd.read_csv('bolsa_familia/dadosTratados/bolsa_familia_por_estado_2013.csv')
bolsa2015

,ano,uf_sigla,uf_nome,qtd_familias_beneficiarias_bolsa_familia,valor_repassado_bolsa_familia,valor_medio_bf,valor_medio_bf_ajustado
0,2013,AC,Acre,868712.0,1.769488e+08,203.69,364.93
1,2013,AL,Alagoas,5169810.0,8.014493e+08,155.02,277.73
2,2013,AM,Amazonas,4044859.0,7.250297e+08,179.25,321.14
3,2013,AP,Amapá,633831.0,1.142520e+08,180.26,322.95
4,2013,BA,Bahia,21387273.0,3.257581e+09,152.31,272.88
5,2013,CE,Ceará,13033169.0,1.974026e+09,151.46,271.35
6,2013,DF,Distrito Federal,1083030.0,1.368821e+08,126.39,226.44
7,2013,ES,Espírito Santo,2379678.0,3.163386e+08,132.93,238.15
8,2013,GO,Goiás,4064472.0,5.584314e+08,137.39,246.15
9,2013,MA,Maranhão,11355024.0,1.961536e+09,172.75,309.50
10,2013,MG,Minas Gerais,13983057.0,1.964722e+09,140.51,251.74
11,2013,MS,Mato Grosso do Sul,1679837.0,2.460936e+08,146.50,262.47
12,2013,MT,Mato Grosso,2178743.0,3.086782e+08,141.68,253.83
13,2013,PA,Pará,9890129.0,1.658481e+09,167.69,300.43
14,2013,PB,Paraíba,6008526.0,9.415646e+08,156.70,280.74
15,2013,PE,Pernambuco,13607853.0,2.001810e+09,147.11,263.56
16,2013,PI,Piauí,5381086.0,9.032638e+08,167.86,300.73
17,2013,PR,Paraná,5153088.0,6.770185e+08,131.38,235.38
18,2013,RJ,Rio de Janeiro,9746902.0,1.402859e+09,143.93,257.86
19,2013,RN,Rio Grande do Norte,4301254.0,6.377425e+08,148.27,265.64
20,2013,RO,Rondônia,1391003.0,2.010703e+08,144.55,258.97
21,2013,RR,Roraima,556898.0,9.297178e+07,166.95,299.10
22,2013,RS,Rio Grande do Sul,5413444.0,7.568389e+08,139.81,250.48
23,2013,SC,Santa Catarina,1713967.0,2.397643e+08,139.89,250.62
24,2013,SE,Sergipe,3197857.0,4.715922e+08,147.47,264.20
25,2013,SP,São Paulo,15529029.0,2.103545e+09,135.46,242.69
26,2013,TO,Tocantins,1643159.0,2.596154e+08,158.00,283.07

In [ ]:
novobolsa2015= bolsa2015[['uf_nome','valor_medio_bf_ajustado']]
novobolsa2015.rename(columns={'uf_nome':'Estado'}, inplace=True)
novobolsa2015

C:\Users\valderez\AppData\Local\Temp\ipykernel_28340\739724054.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  novobolsa2014.rename(columns={'uf_nome':'Estado'}, inplace=True)

                 Estado  valor_medio_bf_ajustado
0                  Acre                   376.98
1               Alagoas                   277.21
2              Amazonas                   326.07
3                 Amapá                   324.54
4                 Bahia                   273.59
5                 Ceará                   270.92
6      Distrito Federal                   230.03
7        Espírito Santo                   239.06
8                 Goiás                   246.74
9              Maranhão                   312.21
10         Minas Gerais                   252.27
11   Mato Grosso do Sul                   260.98
12          Mato Grosso                   253.53
13                 Pará                   301.62
14              Paraíba                   286.67
15           Pernambuco                   264.70
16                Piauí                   305.65
17               Paraná                   234.97
18       Rio de Janeiro                   258.14
19  Rio Grande do Norte                   268.19
20             Rondônia                   253.53
21              Roraima                   304.06
22    Rio Grande do Sul                   250.30
23       Santa Catarina                   250.24
24              Sergipe                   259.55
25            São Paulo                   246.12
26            Tocantins                   281.48

In [76]:
dados1 = pd.read_csv("totais por ano.csv")
dados1

,Estado,Abandono_EF2007,Abandono_EM2007,Abandono_EF2008,Abandono_EM2008,Abandono_EF2009,Abandono_EM2009,Abandono_EF2010,Abandono_EM2010,Abandono_EF2011,...,Abandono_EF2023,Abandono_EM2023,valor_medio_bf_ajustado2007,valor_medio_bf_ajustado2008,valor_medio_bf_ajustado2009,valor_medio_bf_ajustado2010,valor_medio_bf_ajustado2011,valor_medio_bf_ajustado2012,valor_medio_bf_ajustado2013,valor_medio_bf_ajustado2014
0,Acre,4470,5512,6739,5563,7147,5110,6316,5553,5655,...,3684,2453,184.37,208.73,220.64,231.49,257.21,361.93,364.93,376.98
1,Alagoas,48121,32874,37666,28108,33893,32474,26497,29045,46589,...,2634,3143,175.03,194.69,203.34,210.65,228.05,294.55,277.73,277.21
2,Amapá,6930,8513,4976,8183,2142,7810,2892,7385,4585,...,1451,1557,189.19,215.21,227.12,237.48,262.47,343.57,322.95,324.54
3,Amazonas,51244,21077,49366,28578,44081,27148,39370,20588,44493,...,9004,7970,189.42,213.36,223.60,232.74,255.69,338.33,321.14,326.07
4,Bahia,185146,161873,154710,160581,115242,145913,80850,114268,130583,...,29849,24820,178.15,197.81,203.50,209.58,223.29,285.55,272.88,273.59
5,Ceará,50550,78052,41495,72404,34214,68375,23773,53864,37069,...,2269,7175,175.98,195.70,201.81,207.47,221.57,285.50,271.35,270.92
6,Distrito Federal,6205,9456,4688,5294,2943,10915,2936,9599,4601,...,1807,3343,151.22,166.63,174.78,173.56,179.19,248.95,226.44,230.03
7,Espírito Santo,8388,21546,6696,19630,5496,18341,4867,11732,9122,...,1495,2017,155.10,173.37,179.03,188.11,213.13,272.68,238.15,239.06
8,Goiás,33034,53968,25651,48099,20732,36697,14873,35722,24686,...,2605,1345,149.65,169.29,176.16,187.10,211.43,274.43,246.15,246.74
9,Maranhão,65417,69624,63601,67087,41526,54665,36802,56662,46758,...,10457,9639,190.39,212.72,218.36,222.51,239.33,312.96,309.50,312.21
10,Mato Grosso,19031,30531,13108,34355,8188,26731,3425,19425,5330,...,1014,3426,155.02,174.85,180.49,187.21,216.25,281.73,253.83,253.53
11,Mato Grosso do Sul,9386,14765,7303,12941,5914,12558,5172,13567,11519,...,1968,3737,154.82,176.05,181.20,190.73,216.23,286.17,262.47,260.98
12,Minas Gerais,45839,121864,35440,110137,28300,95677,18224,90330,58591,...,16403,35826,157.27,175.46,178.97,186.95,211.09,276.30,251.74,252.27
13,Paraná,8513,53966,8589,59503,6798,46954,4982,37882,25601,...,1366,2420,148.80,166.94,167.71,174.82,203.27,266.25,235.38,234.97
14,Paraíba,52850,38056,49697,37791,37009,34677,27766,32606,42378,...,6812,9104,178.13,198.50,202.85,208.13,221.79,287.56,280.74,286.67
15,Pará,150059,86555,106464,84793,92796,84618,79207,77801,78346,...,22639,1297,191.64,215.54,222.80,228.46,248.53,319.08,300.43,301.62
16,Pernambuco,93803,122590,73627,94676,58743,71280,36042,53255,60789,...,4918,3046,175.93,195.21,201.79,207.83,222.45,281.69,263.56,264.70
17,Piauí,26389,47624,25409,55156,16459,47734,13949,36665,18688,...,2196,2573,181.00,201.38,206.17,210.46,223.69,293.66,300.73,305.65
18,Rio Grande do Norte,26121,48100,25860,43361,20517,38538,16631,32148,28255,...,6557,10328,168.31,188.59,195.31,203.16,218.37,281.35,265.64,268.19
19,Rio Grande do Sul,18083,76730,11293,70459,9464,64161,9241,58882,21047,...,10046,26901,158.84,178.12,182.55,190.54,213.33,277.27,250.48,250.30
20,Rio de Janeiro,69817,115089,64951,118160,56842,107419,41741,95427,48076,...,11671,23302,162.02,181.94,188.59,195.72,216.33,281.40,257.86,258.14
21,Rondônia,9995,9616,6661,9671,4776,8550,4104,8381,8691,...,1591,2784,174.91,194.50,200.88,206.94,227.75,291.36,258.97,253.53
22,Roraima,1673,1886,1021,1800,865,1786,1099,1514,2434,...,1444,1196,188.89,216.25,224.95,233.28,254.17,326.47,299.10,304.06
23,Santa Catarina,4652,21934,2771,22845,2696,21245,1761,23332,7792,...,2824,11750,151.95,169.05,171.86,176.78,206.51,279.09,250.62,250.24
24,Sergipe,24047,21591,17186,21370,13022,17478,7833,16760,16646,...,2753,2174,181.97,204.37,209.00,212.63,227.37,287.72,264.20,259.55
25,São Paulo,18220,96517,18227,85519,12201,80846,24104,97506,53342,...,21373,51316,152.27,169.52,174.74,183.01,207.69,270.35,242.69,246.12
26,Tocantins,5336,10419,4426,10081,3571,7256,2164,6765,4253,...,890,1190,168.76,190.47,195.36,200.97,223.53,298.81,283.07,281.48

In [ ]:
merged_df1 = pd.merge(dados1, novobolsa2015, left_on='Estado', right_on='Estado', how='outer')
merged_df1

,Estado,Abandono_EF2007,Abandono_EM2007,Abandono_EF2008,Abandono_EM2008,Abandono_EF2009,Abandono_EM2009,Abandono_EF2010,Abandono_EM2010,Abandono_EF2011,...,Abandono_EM2023,valor_medio_bf_ajustado2007,valor_medio_bf_ajustado2008,valor_medio_bf_ajustado2009,valor_medio_bf_ajustado2010,valor_medio_bf_ajustado2011,valor_medio_bf_ajustado2012,valor_medio_bf_ajustado2013,valor_medio_bf_ajustado2014,valor_medio_bf_ajustado
0,Acre,4470,5512,6739,5563,7147,5110,6316,5553,5655,...,2453,184.37,208.73,220.64,231.49,257.21,361.93,364.93,376.98,376.98
1,Alagoas,48121,32874,37666,28108,33893,32474,26497,29045,46589,...,3143,175.03,194.69,203.34,210.65,228.05,294.55,277.73,277.21,277.21
2,Amapá,6930,8513,4976,8183,2142,7810,2892,7385,4585,...,1557,189.19,215.21,227.12,237.48,262.47,343.57,322.95,324.54,324.54
3,Amazonas,51244,21077,49366,28578,44081,27148,39370,20588,44493,...,7970,189.42,213.36,223.60,232.74,255.69,338.33,321.14,326.07,326.07
4,Bahia,185146,161873,154710,160581,115242,145913,80850,114268,130583,...,24820,178.15,197.81,203.50,209.58,223.29,285.55,272.88,273.59,273.59
5,Ceará,50550,78052,41495,72404,34214,68375,23773,53864,37069,...,7175,175.98,195.70,201.81,207.47,221.57,285.50,271.35,270.92,270.92
6,Distrito Federal,6205,9456,4688,5294,2943,10915,2936,9599,4601,...,3343,151.22,166.63,174.78,173.56,179.19,248.95,226.44,230.03,230.03
7,Espírito Santo,8388,21546,6696,19630,5496,18341,4867,11732,9122,...,2017,155.10,173.37,179.03,188.11,213.13,272.68,238.15,239.06,239.06
8,Goiás,33034,53968,25651,48099,20732,36697,14873,35722,24686,...,1345,149.65,169.29,176.16,187.10,211.43,274.43,246.15,246.74,246.74
9,Maranhão,65417,69624,63601,67087,41526,54665,36802,56662,46758,...,9639,190.39,212.72,218.36,222.51,239.33,312.96,309.50,312.21,312.21
10,Mato Grosso,19031,30531,13108,34355,8188,26731,3425,19425,5330,...,3426,155.02,174.85,180.49,187.21,216.25,281.73,253.83,253.53,253.53
11,Mato Grosso do Sul,9386,14765,7303,12941,5914,12558,5172,13567,11519,...,3737,154.82,176.05,181.20,190.73,216.23,286.17,262.47,260.98,260.98
12,Minas Gerais,45839,121864,35440,110137,28300,95677,18224,90330,58591,...,35826,157.27,175.46,178.97,186.95,211.09,276.30,251.74,252.27,252.27
13,Paraná,8513,53966,8589,59503,6798,46954,4982,37882,25601,...,2420,148.80,166.94,167.71,174.82,203.27,266.25,235.38,234.97,234.97
14,Paraíba,52850,38056,49697,37791,37009,34677,27766,32606,42378,...,9104,178.13,198.50,202.85,208.13,221.79,287.56,280.74,286.67,286.67
15,Pará,150059,86555,106464,84793,92796,84618,79207,77801,78346,...,1297,191.64,215.54,222.80,228.46,248.53,319.08,300.43,301.62,301.62
16,Pernambuco,93803,122590,73627,94676,58743,71280,36042,53255,60789,...,3046,175.93,195.21,201.79,207.83,222.45,281.69,263.56,264.70,264.70
17,Piauí,26389,47624,25409,55156,16459,47734,13949,36665,18688,...,2573,181.00,201.38,206.17,210.46,223.69,293.66,300.73,305.65,305.65
18,Rio Grande do Norte,26121,48100,25860,43361,20517,38538,16631,32148,28255,...,10328,168.31,188.59,195.31,203.16,218.37,281.35,265.64,268.19,268.19
19,Rio Grande do Sul,18083,76730,11293,70459,9464,64161,9241,58882,21047,...,26901,158.84,178.12,182.55,190.54,213.33,277.27,250.48,250.30,250.30
20,Rio de Janeiro,69817,115089,64951,118160,56842,107419,41741,95427,48076,...,23302,162.02,181.94,188.59,195.72,216.33,281.40,257.86,258.14,258.14
21,Rondônia,9995,9616,6661,9671,4776,8550,4104,8381,8691,...,2784,174.91,194.50,200.88,206.94,227.75,291.36,258.97,253.53,253.53
22,Roraima,1673,1886,1021,1800,865,1786,1099,1514,2434,...,1196,188.89,216.25,224.95,233.28,254.17,326.47,299.10,304.06,304.06
23,Santa Catarina,4652,21934,2771,22845,2696,21245,1761,23332,7792,...,11750,151.95,169.05,171.86,176.78,206.51,279.09,250.62,250.24,250.24
24,Sergipe,24047,21591,17186,21370,13022,17478,7833,16760,16646,...,2174,181.97,204.37,209.00,212.63,227.37,287.72,264.20,259.55,259.55
25,São Paulo,18220,96517,18227,85519,12201,80846,24104,97506,53342,...,51316,152.27,169.52,174.74,183.01,207.69,270.35,242.69,246.12,246.12
26,Tocantins,5336,10419,4426,10081,3571,7256,2164,6765,4253,...,1190,168.76,190.47,195.36,200.97,223.53,298.81,283.07,281.48,281.48

In [94]:
totalTotal= merged_df1

In [102]:
totalTotal.to_csv("totais por ano.csv", sep=",", index=False)