## Bibliotecas para fazer a análise de regressão e implementar outros dados no mapa

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
import geobr
from sklearn.metrics import mean_squared_error, r2_score

In [2]:
df = pd.read_csv("analise_robusta.csv")

## 1- Juntando passo a passo as variáveis em um dataframe só

In [ ]:

abandono_ef = df.melt(
    id_vars=["UF"],  
    value_vars=[col for col in df.columns if "Abandono_EM" in col], 
    var_name="Ano",  
    value_name="Abandono_EM"  
)
abandono_ef["Ano"] = abandono_ef["Ano"].str.extract(r'(\d{4})').astype(int)


valor_bf = df.melt(
    id_vars=["UF"],
    value_vars=[col for col in df.columns if "valor_medio_bf_ajustado_" in col],
    var_name="Ano",
    value_name="Valor_medio_BF"
)
valor_bf["Ano"] = valor_bf["Ano"].str.extract(r'(\d{4})').astype(int)


df_final = pd.merge(abandono_ef, valor_bf, on=["UF", "Ano"])

print(df_final.head())

   UF   Ano  Abandono_EM  Valor_medio_BF
0  AC  2007         5512          184.37
1  AL  2007        32874          175.03
2  AP  2007         8513          189.19
3  AM  2007        21077          189.42
4  BA  2007       161873          178.15

In [ ]:
IDHM_EDUCACAO = df.melt(
    id_vars=["UF"],
    value_vars=[col for col in df.columns if "IDHM Educação" in col],
    var_name="Ano",
    value_name="IDHM Educação"
)
IDHM_EDUCACAO ["Ano"] = IDHM_EDUCACAO["Ano"].str.extract(r'(\d{4})').astype(int)



df_final = pd.merge(df_final, IDHM_EDUCACAO, on=["UF", "Ano"])

print(df_final.head())

   UF   Ano  Abandono_EM  Valor_medio_BF  IDHM Educação
0  AC  2012         4006          361.93          0.649
1  AL  2012        23988          294.55          0.587
2  AP  2012         6925          343.57          0.659
3  AM  2012        21056          338.33          0.632
4  BA  2012        83059          285.55          0.593

In [ ]:
IDHM_RENDA = df.melt(
    id_vars=["UF"],
    value_vars=[col for col in df.columns if "IDHM Renda" in col],
    var_name="Ano",
    value_name="IDHM Renda"
)
IDHM_RENDA["Ano"] = IDHM_RENDA["Ano"].str.extract(r'(\d{4})').astype(int)


df_final = pd.merge(df_final, IDHM_RENDA, on=["UF", "Ano"])


print(df_final.head())

   UF   Ano  Abandono_EM  Valor_medio_BF  IDHM Educação  IDHM Renda
0  AC  2012         4006          361.93          0.649       0.670
1  AL  2012        23988          294.55          0.587       0.627
2  AP  2012         6925          343.57          0.659       0.673
3  AM  2012        21056          338.33          0.632       0.683
4  BA  2012        83059          285.55          0.593       0.666

In [ ]:
INDICE_ATKINSON= df.melt(
    id_vars=["UF"],
    value_vars=[col for col in df.columns if "Índice de Atkinson - Renda" in col],
    var_name="Ano",
    value_name="Índice de Atkinson Renda"
)
INDICE_ATKINSON["Ano"] = INDICE_ATKINSON["Ano"].str.extract(r'(\d{4})').astype(int)

df_final = pd.merge(df_final, INDICE_ATKINSON, on=["UF", "Ano"])

print(df_final.head())

   UF   Ano  Abandono_EM  Valor_medio_BF  IDHM Educação  IDHM Renda  \
0  AC  2012         4006          361.93          0.649       0.670
1  AL  2012        23988          294.55          0.587       0.627
2  AP  2012         6925          343.57          0.659       0.673
3  AM  2012        21056          338.33          0.632       0.683
4  BA  2012        83059          285.55          0.593       0.666

   Índice de Atkinson Renda
0                     0.422
1                     0.352
2                     0.361
3                     0.417
4                     0.405

In [ ]:
INDICE_ATKINSON= df.melt(
    id_vars=["UF"],
    value_vars=[col for col in df.columns if "Índice de Atkinson - Educação" in col],
    var_name="Ano",
    value_name="Índice de Atkinson Educacao"
)
INDICE_ATKINSON["Ano"] = INDICE_ATKINSON["Ano"].str.extract(r'(\d{4})').astype(int)

df_final = pd.merge(df_final, INDICE_ATKINSON, on=["UF", "Ano"])

print(df_final.head())

   UF   Ano  Abandono_EM  Valor_medio_BF  IDHM Educação  IDHM Renda  \
0  AC  2012         4006          361.93          0.649       0.670
1  AL  2012        23988          294.55          0.587       0.627
2  AP  2012         6925          343.57          0.659       0.673
3  AM  2012        21056          338.33          0.632       0.683
4  BA  2012        83059          285.55          0.593       0.666

   Índice de Atkinson Renda  Índice de Atkinson Educacao
0                     0.422                        0.281
1                     0.352                        0.296
2                     0.361                        0.184
3                     0.417                        0.202
4                     0.405                        0.275

In [ ]:

QTD_FAMILIAS= df.melt(
    id_vars=["UF"],
    value_vars=[col for col in df.columns if "qtd_familias_beneficiarias_bolsa_familia_ajustado_" in col],
    var_name="Ano",
    value_name="QTD_FAMILIAS_BF"
)
QTD_FAMILIAS["Ano"] = QTD_FAMILIAS["Ano"].str.extract(r'(\d{4})').astype(int)

df_final = pd.merge(df_final,QTD_FAMILIAS, on=["UF", "Ano"])

print(df_final.head())

   UF   Ano  Abandono_EM  Valor_medio_BF  IDHM Educação  IDHM Renda  \
0  AC  2012         4006          361.93          0.649       0.670
1  AL  2012        23988          294.55          0.587       0.627
2  AP  2012         6925          343.57          0.659       0.673
3  AM  2012        21056          338.33          0.632       0.683
4  BA  2012        83059          285.55          0.593       0.666

   Índice de Atkinson Renda  Índice de Atkinson Educacao  QTD_FAMILIAS_BF
0                     0.422                        0.281          67021.0
1                     0.352                        0.296         429494.0
2                     0.361                        0.184          52285.0
3                     0.417                        0.202         323646.0
4                     0.405                        0.275        1777116.0

In [ ]:
gini = pd.read_csv("dadosUsadosParaMerge/idhm_gini_estado")

IndiciDeGINI= gini.melt(
    id_vars=["UF"],
    value_vars=[col for col in gini.columns if "Índice de Gini " in col],
    var_name="Ano",
    value_name="IndiceDeGINI"
)
IndiciDeGINI["Ano"] = IndiciDeGINI["Ano"].str.extract(r'(\d{4})').astype(int)

df_final = pd.merge(df_final,IndiciDeGINI, on=["UF", "Ano"])

df_final.head()

,UF,Ano,Abandono_EM,Valor_medio_BF,IDHM Educação,IDHM Renda,Índice de Atkinson Renda,Índice de Atkinson Educacao,QTD_FAMILIAS_BF,rendaPercapta,IndiceDeGINI
0,AC,2012,4006,361.93,0.649,0.670,0.422,0.281,67021.0,516.75,0.566
1,AL,2012,23988,294.55,0.587,0.627,0.352,0.296,429494.0,395.06,0.503
2,AP,2012,6925,343.57,0.659,0.673,0.361,0.184,52285.0,528.23,0.528
3,AM,2012,21056,338.33,0.632,0.683,0.417,0.202,323646.0,559.44,0.589
4,BA,2012,83059,285.55,0.593,0.666,0.405,0.275,1777116.0,503.29,0.563

In [ ]:
taxas = pd.read_csv("dadosUsadosParaMerge/TaxasDeDesocupacaoOcupacaoParticipacao.csv")
TAXADESOCUPACAO = taxas[["UF","Ano","Taxa_Desocupacao"]]

df_final = pd.merge(df_final,TAXADESOCUPACAO, on=["UF", "Ano"])

df_final.head()

,UF,Ano,Abandono_EM,Valor_medio_BF,IDHM Educação,IDHM Renda,Índice de Atkinson Renda,Índice de Atkinson Educacao,QTD_FAMILIAS_BF,rendaPercapta,IndiceDeGINI,Taxa_Desocupacao
0,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,9.3
1,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,9.1
2,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,7.7
3,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,8.1
4,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,10.9

In [ ]:
TAXADEOCUPACAO = taxas[["UF","Ano","Nivel_Ocupacao"]]

df_final = pd.merge(df_final,TAXADEOCUPACAO, on=["UF", "Ano"])


df_final.head()

,UF,Ano,Abandono_EM,Valor_medio_BF,IDHM Educação,IDHM Renda,Índice de Atkinson Renda,Índice de Atkinson Educacao,QTD_FAMILIAS_BF,rendaPercapta,IndiceDeGINI,Taxa_Desocupacao,Nivel_Ocupacao
0,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,9.3,53.2
1,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,9.3,55.7
2,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,9.3,55.5
3,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,9.3,56.3
4,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,9.3,54.1

In [ ]:
TAXAPARTICIPACAO = taxas[["UF","Ano","Taxa_Participacao"]]


df_final = pd.merge(df_final,TAXAPARTICIPACAO, on=["UF", "Ano"])

df_final.head()
print(df_final.columns)

,UF,Ano,Abandono_EM,Valor_medio_BF,IDHM Educação,IDHM Renda,Índice de Atkinson Renda,Índice de Atkinson Educacao,QTD_FAMILIAS_BF,rendaPercapta,IndiceDeGINI,Taxa_Desocupacao,Nivel_Ocupacao,Taxa_Participacao
0,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,9.3,53.2,58.6
1,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,9.3,53.2,61.3
2,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,9.3,53.2,60.3
3,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,9.3,53.2,61.3
4,AC,2012,4006,361.93,0.649,0.67,0.422,0.281,67021.0,516.75,0.566,9.3,53.2,60.8

## 2 - Fazendo a análise OLS do dataframe

### Para ensino fundamental:

In [5]:
X = df_final[['Valor_medio_BF', 'IDHM Educação', 'Índice de Atkinson Educacao', 'Taxa_Desocupacao',
'Taxa_Participacao', 'Nivel_Ocupacao', 'Índice de Atkinson Renda', 'QTD_FAMILIAS_BF']]
y = df_final["Abandono_EF"]
X = sm.add_constant(X)

modelo = sm.OLS(y, X).fit()
print(modelo.summary())

NameError: name 'df_final' is not defined

### Para ensino médio:

In [ ]:
X = df_final[['Valor_medio_BF', 'IDHM Educação','IDHM Renda', 'Índice de Atkinson Renda', 'Índice de Atkinson Educacao', 
 'IndiceDeGINI', 'Taxa_Desocupacao','Nivel_Ocupacao', 'Taxa_Participacao','QTD_FAMILIAS_BF']]
y = df_final["Abandono_EM"]
X = sm.add_constant(X)



modelo = sm.OLS(y, X).fit()
print(modelo.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            Abandono_EM   R-squared:                       0.686
Model:                            OLS   Adj. R-squared:                  0.686
Method:                 Least Squares   F-statistic:                 3.430e+06
Date:                Sun, 20 Apr 2025   Prob (F-statistic):               0.00
Time:                        15:20:41   Log-Likelihood:            -1.8435e+08
No. Observations:            17280000   AIC:                         3.687e+08
Df Residuals:                17279988   BIC:                         3.687e+08
Df Model:                          11
Covariance Type:            nonrobust
===============================================================================================
                                  coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------
const                        1.741e+05    193.110    901.694      0.000    1.74e+05    1.75e+05
Valor_medio_BF                 73.2479      0.042   1754.889      0.000      73.166      73.330
IDHM Educação                -8.14e+04     73.618  -1105.734      0.000   -8.15e+04   -8.13e+04
IDHM Renda                  -1.809e+05    310.096   -583.459      0.000   -1.82e+05    -1.8e+05
Índice de Atkinson Renda    -1.022e+05    216.438   -472.203      0.000   -1.03e+05   -1.02e+05
Índice de Atkinson Educacao -1.197e+05    102.625  -1166.170      0.000    -1.2e+05   -1.19e+05
rendaPercapta                  34.0618      0.056    605.122      0.000      33.952      34.172
IndiceDeGINI                 1.894e+04    242.242     78.174      0.000    1.85e+04    1.94e+04
Taxa_Desocupacao             -160.4180      0.792   -202.474      0.000    -161.971    -158.865
Nivel_Ocupacao                193.6622      0.750    258.344      0.000     192.193     195.131
Taxa_Participacao             249.7404      0.899    277.749      0.000     247.978     251.503
QTD_FAMILIAS_BF                 0.0319   6.05e-06   5270.920      0.000       0.032       0.032
==============================================================================
Omnibus:                  1478770.201   Durbin-Watson:                   0.001
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          5853960.887
Skew:                           0.364   Prob(JB):                         0.00
Kurtosis:                       5.757   Cond. No.                     1.05e+08
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.05e+08. This might indicate that there are
strong multicollinearity or other numerical problems.

### 3 - Esse código tem a finalidade de filtrar os dados médios para serem implementados na geoBR

#### Filtrando as médias para colocar no geobr

##### IDHM Renda e Educação

In [ ]:
df = pd.read_csv('dadosUsadosParaMerge/idhm_consolidado.csv')

soma_educ = df.filter(like='IDHM Renda').sum(axis=1).round(2)
df['Media_IDHM_Renda'] = soma_educ / 10 
df_resultado = df[['Estado', 'UF', 'Media_IDHM_Renda']].sort_values('Media_IDHM_Renda', ascending=False)

df_resultado.to_csv('Media_IDHM_Educação.csv', index=False, encoding='utf-8-sig', float_format='%.3f')

In [ ]:
df = pd.read_csv('dadosUsadosParaMerge/idhm_consolidado.csv')

soma_educ = df.filter(like='IDHM Educação ').sum(axis=1).round(2)
df['Media_IDHM_Educacao'] = soma_educ / 10 
df_resultado = df[['Estado', 'UF', 'Media_IDHM_Educacao']].sort_values('Media_IDHM_Educacao', ascending=False)

df_resultado.to_csv('Media_IDHM_Renda.csv', index=False, encoding='utf-8-sig', float_format='%.3f')

#### Atkinson de Renda e Educação

In [ ]:
df = pd.read_csv('dadosUsadosParaMerge/idhm_consolidadoAtkinson.csv')

soma_educ = df.filter(like='Indici de Atkison - Educação').sum(axis=1).round(2)
df['Media_Indice_Atkison_Educacao'] = soma_educ / 10  
df_resultado = df[['Estado', 'UF', 'Media_Indice_Atkison_Educacao']].sort_values('Media_Indice_Atkison_Educacao', ascending=False)


df_resultado.to_csv('Media_IDHM_Educação_Atkinson.csv', index=False, encoding='utf-8-sig', float_format='%.3f')

In [ ]:
df = pd.read_csv('dadosUsadosParaMerge/idhm_consolidadoAtkinson.csv')

soma_educ = df.filter(like='Indici de Atkison - Renda').sum(axis=1).round(2)
df['Media_Indice_Atkison_Renda'] = soma_educ / 10 
df_resultado = df[['Estado', 'UF', 'Media_Indice_Atkison_Renda']].sort_values('Media_Indice_Atkison_Renda', ascending=False)

df_resultado.to_csv('Media_IDHM_Renda_Atkinson.csv', index=False, encoding='utf-8-sig', float_format='%.3f')

#### índice de Gini

In [ ]:
df = pd.read_csv('dadosUsadosParaMerge/idhm_gini_estado.csv')

soma_educ = df.filter(like='Media_Indice_Gini').sum(axis=1).round(2)
df['Media_Indice_Gini'] = soma_educ / 10 
df_resultado = df[['Estado', 'UF', 'Media_Indice_Gini']].sort_values('Media_Indice_Gini', ascending=False)

df_resultado.to_csv('media_gini.csv', index=False, encoding='utf-8-sig', float_format='%.3f')

#### Total de famílias beneficiadas

In [ ]:
df = pd.read_csv('analise_robusta2.csv')

colunas_anos = ['qtd_familias_beneficiarias_bolsa_familia_ajustado_2012','qtd_familias_beneficiarias_bolsa_familia_ajustado_2013','qtd_familias_beneficiarias_bolsa_familia_ajustado_2014','qtd_familias_beneficiarias_bolsa_familia_ajustado_2015','qtd_familias_beneficiarias_bolsa_familia_ajustado_2016','qtd_familias_beneficiarias_bolsa_familia_ajustado_2017','qtd_familias_beneficiarias_bolsa_familia_ajustado_2018','qtd_familias_beneficiarias_bolsa_familia_ajustado_2019','qtd_familias_beneficiarias_bolsa_familia_ajustado_2020','qtd_familias_beneficiarias_bolsa_familia_ajustado_2021']

df['QTD_DE_FAMILIAS_média'] = df[colunas_anos].sum(axis=1) / len(colunas_anos)
df_media = df.groupby('UF')['QTD_DE_FAMILIAS_média'].mean()

df_media.head()

#### Valor médio do bolsa família de acordo com IPCA IBGE

In [ ]:
df = pd.read_csv('analise_robusta2.csv')

colunas_anos = ['valor_medio_bf_ajustado_2012','valor_medio_bf_ajustado_2013','valor_medio_bf_ajustado_2014','valor_medio_bf_ajustado_2015','valor_medio_bf_ajustado_2016','valor_medio_bf_ajustado_2017','valor_medio_bf_ajustado_2018','valor_medio_bf_ajustado_2019','valor_medio_bf_ajustado_2020','valor_medio_bf_ajustado_2021',]

df['VALOR MEDIO REPASSADO'] = df[colunas_anos].sum(axis=1) / len(colunas_anos)

df_media = df.groupby('UF')['VALOR MEDIO REPASSADO'].mean()
df_media.head()

#### Partindo para colocar os dados no geobr. Foi utilizado o mesmo código com reajuste aos nomes das planilhas e suas colunas utilizadas

In [ ]:
estados = geobr.read_state(year=2018)

df_muni = pd.read_csv("dados_medios/Media_IDHM_Renda.csv")

df_muni["Estado"] = df_muni["UF"].str.lower() 
estados["sigla"] = estados["abbrev_state"].str.lower() 
estados = estados.merge(df_muni, left_on="sigla", right_on="Estado", how="left")


plt.rcParams.update({"font.size": 8})
fig, ax = plt.subplots(figsize=(12, 10), dpi=150)

estados.plot(
    column="Media_IDHM_Renda",
    cmap="YlGn",
    legend=True,
    legend_kwds={
        "label": "IDHM Renda",
        "orientation": "horizontal",
        "shrink": 0.6,
    },
    ax=ax
)


ax.set_title("Média do IDHM de renda por estado (2012-2021)")
ax.axis("off")

  CD_UF     NM_UF SIGLA_UF CD_REGIAO NM_REGIAO     AREA_KM2  \
0    11  Rondônia       RO         1     Norte   237754.171
1    12      Acre       AC         1     Norte   164173.525
2    13  Amazonas       AM         1     Norte  1559256.365
3    14   Roraima       RR         1     Norte   223644.534
4    15      Pará       PA         1     Norte  1245870.242

                                            geometry
0  POLYGON ((-63.56494 -12.50309, -63.56925 -12.5...
1  POLYGON ((-69.42369 -10.92668, -69.42421 -10.9...
2  POLYGON ((-67.51732 -9.56071, -67.51776 -9.560...
3  POLYGON ((-60.04183 0.25298, -60.04683 0.23213...
4  MULTIPOLYGON (((-51.48817 -9.76058, -51.72427 ...